name: 'Delta'
description: 'A GitHub Action for capturing benchmark data and tracking its variation against a baseline'
inputs:
  base_branch:
    default: main
    description: 'Name of the base branch'
  title:
    default: Delta results
    description: 'Title used in the comments'
  token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
