name: 'Delta'
description: 'A GitHub Action for capturing benchmark data and tracking its variation against a baseline'
inputs:
  base_branch:
    default: main
    description: 'Name of the base branch'
    required: false
  title:
    default: Delta results
    description: 'Title used in the comments'
    required: false
  token:
    description: 'GitHub access token'
    required: false
    default: ${{ github.token }}
  pr_number:
    description: 'The PR this run is associated with (for `workflow_run`)'
    required: false
    default: ''
  style:
    description: 'The rendering style to use when commenting on PRs (options: text, graph)'
    required: false
    default: 'graph'
runs:
  using: 'node16'
  main: 'dist/index.js'
